# Generated by Django 5.2.13 on 2026-05-04 10:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=90, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DemoProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=80)),
                ('bio', models.TextField(blank=True)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('condition', models.CharField(choices=[('new', 'Новое'), ('excellent', 'Отличное'), ('good', 'Хорошее'), ('fair', 'Нормальное')], default='good', max_length=20)),
                ('city', models.CharField(max_length=80)),
                ('estimated_value', models.PositiveIntegerField(help_text='Оценочная ценность в условных баллах')),
                ('exchange_terms', models.TextField(blank=True)),
                ('desired_keywords', models.CharField(help_text='Что пользователь хочет получить: слова через запятую или короткая фраза', max_length=220)),
                ('acceptable_city', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('active', 'Активно'), ('in_deal', 'В обмене'), ('archived', 'В архиве'), ('blocked', 'Заблокировано')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='exchange.category')),
                ('desired_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='desired_by_listings', to='exchange.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='exchange.demoprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает ответа'), ('accepted', 'Принята'), ('rejected', 'Отклонена'), ('cancelled', 'Отменена'), ('completed', 'Завершена')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_requests', to='exchange.demoprofile')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_requests', to='exchange.demoprofile')),
                ('offered_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_in_requests', to='exchange.listing')),
                ('requested_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_in_requests', to='exchange.listing')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/')),
                ('alt_text', models.CharField(blank=True, max_length=160)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='exchange.listing')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to='exchange.demoprofile')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='exchange.exchangerequest')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='exchange.demoprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('exchange', 'author', 'target')},
            },
        ),
    ]
