# Generated by Django 5.2.13 on 2026-05-04 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_listing_external_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='estimated_value',
        ),
    ]
