# Generated by Django 5.2.14 on 2026-05-10 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('wrong_category', 'Неверная категория'), ('fraud', 'Подозрение на мошенничество'), ('forbidden', 'Запрещенный товар'), ('offensive', 'Оскорбительное содержание'), ('other', 'Другое')], max_length=40)),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_review', 'На рассмотрении'), ('resolved', 'Рассмотрена'), ('rejected', 'Отклонена')], default='new', max_length=20)),
                ('resolution', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='exchange.listing')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_created', to='exchange.demoprofile')),
                ('target_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints_received', to='exchange.demoprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
