# Generated by Django 5.2.14 on 2026-05-11 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0007_alter_category_options_alter_complaint_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='reason',
            field=models.CharField(choices=[('wrong_category', 'Неверная категория'), ('wrong_description', 'Описание не соответствует товару'), ('fraud', 'Подозрение на мошенничество'), ('forbidden', 'Запрещенный товар'), ('offensive', 'Оскорбительное содержание'), ('fake_profile', 'Недостоверный профиль'), ('spam', 'Спам или навязчивые сообщения'), ('other', 'Другое')], max_length=40, verbose_name='Причина'),
        ),
    ]
