# Generated by Django 5.2.14 on 2026-05-20 16:35

import django.db.models.deletion
from django.db import migrations, models


def fill_desired_categories(apps, schema_editor):
    Category = apps.get_model('exchange', 'Category')
    Listing = apps.get_model('exchange', 'Listing')
    through_model = Listing.desired_categories.through

    Category.objects.get_or_create(name='Другое', defaults={'slug': 'drugoe'})
    rows = [
        through_model(listing_id=listing.pk, category_id=listing.desired_category_id)
        for listing in Listing.objects.exclude(desired_category_id__isnull=True)
    ]
    through_model.objects.bulk_create(rows, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0008_alter_complaint_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerequest',
            name='initiator_contact',
            field=models.CharField(blank=True, max_length=220, verbose_name='Способ связи инициатора'),
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='receiver_contact',
            field=models.CharField(blank=True, max_length=220, verbose_name='Способ связи получателя'),
        ),
        migrations.AddField(
            model_name='listing',
            name='desired_categories',
            field=models.ManyToManyField(blank=True, related_name='desired_by_multiple_listings', to='exchange.category', verbose_name='Желаемые категории'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('new', 'Новое'), ('excellent', 'Как новое'), ('good', 'Хорошее'), ('fair', 'Есть следы использования'), ('needs_repair', 'Требует ремонта')], default='good', max_length=20, verbose_name='Состояние'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='exchange.listing', verbose_name='Объявление')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='exchange.demoprofile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Избранное объявление',
                'verbose_name_plural': 'Избранные объявления',
                'ordering': ['-created_at'],
                'unique_together': {('profile', 'listing')},
            },
        ),
        migrations.RunPython(fill_desired_categories, migrations.RunPython.noop),
    ]
